#!name=网易读书

#!desc=sc



[Script]

wyds= type=http-response,pattern=^https?:\/\/p\.du\.163\.com\/gain\/readtime\/info,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/yywnds.js

[MITM]

hostname = %APPEND% p.du.163.com

*******************************/

var body=$response.body;

ojbk = body.replace(/tradeEndTime\":\d+/g,'tradeEndTime":4092599349000');

$done(ojbk);
